name: Daily Music Chart Crawler

on:
  schedule:
    - cron: '0 22 * * *' # 매일 오전 7시(KST, UTC+9)
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check backend folder
        run: |
          ls -al
          ls -al backend
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install venv and pip dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-venv python3-pip
      - name: Create virtual environment
        run: python3 -m venv backend/venv
      - name: Fix python3 symlink in venv (if needed)
        run: |
          if [ ! -f backend/venv/bin/python3 ] && [ -f backend/venv/bin/python ]; then
            ln -s python backend/venv/bin/python3
          fi
      - name: List venv bin directory
        run: ls -al backend/venv/bin
      - name: Install dependencies
        run: backend/venv/bin/pip install -r backend/requirements.txt
      - name: Run DB init
        run: backend/venv/bin/python backend/db/init_db.py
      - name: Run Spotify Crawler
        run: backend/venv/bin/python backend/crawler/spotify.py
      - name: Run YouTube Crawler
        run: backend/venv/bin/python backend/crawler/youtube.py
      - name: Run SoundCloud Crawler
        run: backend/venv/bin/python backend/crawler/soundcloud.py
      - name: Run Beatport Crawler
        run: backend/venv/bin/python backend/crawler/beatport.py
      - name: Export chart data to JSON
        run: backend/venv/bin/python backend/main.py
      - name: Commit & Push data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data
          git add musictrend.db
          git commit -m '자동 크롤링 데이터 업데이트' || echo 'No changes'
          git push
