name: Daily Music Chart Crawler

on:
  schedule:
    - cron: '0 22 * * *' # 매일 오전 7시(KST, UTC+9)
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Set up venv
        run: |
          cd backend
          python -m venv venv
          ls -al venv/bin
      - name: Install dependencies
        run: |
          cd backend
          ./venv/bin/pip install -r requirements.txt
      - name: Run DB init
        run: backend/venv/bin/python backend/db/init_db.py
      - name: Run Spotify Crawler
        run: backend/venv/bin/python backend/crawler/spotify.py
      - name: Run YouTube Crawler
        run: backend/venv/bin/python backend/crawler/youtube.py
      - name: Run SoundCloud Crawler
        run: backend/venv/bin/python backend/crawler/soundcloud.py
      - name: Run Beatport Crawler
        run: backend/venv/bin/python backend/crawler/beatport.py
      - name: Export chart data to JSON
        run: backend/venv/bin/python backend/main.py
      - name: Commit & Push data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data
          git add musictrend.db
          git commit -m '자동 크롤링 데이터 업데이트' || echo 'No changes'
          git push
